name: wearecubans
favicon: null
layout_spectrum: 0.8715998595580459
typography_spectrum: 0.9453814467415214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.32461985503323376
  lightness: 0.07717469823546708
  saturation: 0.35076418705284595
  rhythmicContrast: 0.11196123971603811
purpose: []
